env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
ignorePatterns:
  - '**/node_modules/**'
rules:
  # インデントはスペース2つ
  indent:
    - error
    - 2
  # 改行のスタイルはLF
  linebreak-style:
    - error
    - unix
  # シングルクォートを使用
  quotes:
    - error
    - single
  # 行末のセミコロンを禁止
  semi:
    - error
    - never
