version: "3.6"

services:
  redis:
    ports:
      - "6379:6379"
    image: ghcr.io/raihara3/redis:6.0.10
    volumes:
      - /redis-data:/data

  nextjs-first:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/build

  nextjs-second:
    ports:
      - "3001:3001"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/build
    command:
      - start-second
