version: "3.6"

services:
  redis:
    ports:
      - "6379:6379"
    image: ghcr.io/raihara3/redis:6.0.10
    volumes:
      - /redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  nextjs:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
