version: "3.6"

services:
  redis:
    ports:
      - "6379:6379"
    image: ghcr.io/raihara3/redis:6.0.10

  nextjs:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
