version: "3.6"

services:
  redis:
    ports:
      - "6379:6379"
    image: ghcr.io/raihara3/redis:6.0.10
    volumes:
      - /redis-data:/data

  nextjs:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    volumes:
      - .:/build
      - /build/node_modules
